project_id = "gdnmzobphsrvxwfiulpo"

[functions.project-helper]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[auth]
site_url = "https://www.nexstepedu.com"
additional_redirect_urls = ["https://www.nexstepedu.com/**", "https://nexstepedu.com/**", "https://id-preview--dc92c9c1-5be7-43c9-ba89-ba41172f59bf.lovable.app/**"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.invite]
subject = "NexStep | You've Been Invited"
content_path = "./templates/invite.html"

[auth.email.template.confirmation]
subject = "NexStep | Confirm Your Email"
content_path = "./templates/confirmation.html"

[auth.email.template.recovery]
subject = "NexStep | Reset Your Password"
content_path = "./templates/recovery.html"

[auth.email.template.magic_link]
subject = "NexStep | Your Login Link"
content_path = "./templates/magic_link.html"

[auth.email.template.email_change]
subject = "NexStep | Confirm Email Change"
content_path = "./templates/email_change.html"

[functions.process-email-queue]
verify_jwt = true
